### ISSUE TITLE
Make project-containers clickable

### ISSUE THREAD

**Issue by nikesh-r** [nikesh-r/nikesh.dev#1]
Make the project-item-containers clickable so that it opens the actual project repo or hosted website.
solution- shift the parent container inside the a tag.

**Comment by godwin-morwin** [comment]
Hi, I'm Godwin, it will be a pleasure to contribute to this.

**Comment by nikesh-r** [comment]
> Make the project-item-containers clickable so that it opens the actual project repo or hosted website.
> solution- shift the parent container inside the a tag.

**Comment by nikesh-r** [comment]
> Hi, I'm Godwin, it will be a pleasure to contribute to this.

Hi Godwin!
Thanks for you interest.
I will be glad if you contributed to my portfolio.
As you can see in the issue title and description itself, I just want to make the project-item-container clickable to open their respective project-item--btn links.
